# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 12:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=50, verbose_name='adress')),
                ('zipcode', models.IntegerField(verbose_name='zipcode')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('website', models.TextField(max_length=50, verbose_name='website')),
                ('contact_email', models.EmailField(max_length=50, verbose_name='contact_email')),
                ('skills', models.TextField(max_length=500, verbose_name='skills')),
                ('interests', models.TextField(max_length=500, verbose_name='interests')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
