# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.ImageField(default=1, upload_to=b'', verbose_name='avatar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='website',
            field=models.CharField(max_length=50, verbose_name='website'),
        ),
    ]
